"""ElevenLabs voices — UEFN Ducky desktop plugin.

Registers a TTS synthesizer + a dynamic voice lister so ElevenLabs voices show up in
every voice picker (per-ducky and the default voice). Speech is generated by calling
the ElevenLabs HTTP API with the user's key; nothing is bundled or phoned home except
the request to ElevenLabs itself.

The API key lives in the app's encrypted credentials store (never in this package),
under the manifest secret key ``elevenlabs_api_key``. The chosen model is a plain
plugin pref (``model_id``) written by the ElevenLabs settings tab.
"""

from __future__ import annotations

import base64
import json
import logging
import time
import urllib.error
import urllib.request
from typing import Any

log = logging.getLogger("uefn.plugin.elevenlabs")

PLUGIN_ID = "elevenlabs"
SECRET_KEY = "elevenlabs_api_key"
API_BASE = "https://api.elevenlabs.io/v1"
DEFAULT_MODEL = "eleven_multilingual_v2"
# Fallback only — the picker always passes a concrete voice id (Sarah, premade).
DEFAULT_VOICE_ID = "EXAVITQu4vr4xnSDxMaL"

# Short-lived cache for the account voice list, busted when the API key changes.
_VOICE_CACHE: dict[str, Any] = {"at": 0.0, "key_fp": "", "voices": []}
_VOICE_TTL_SECONDS = 60.0


def _api_key() -> str:
    from backend.agent.secrets import get_key

    return (get_key(SECRET_KEY) or "").strip()


def _model_id() -> str:
    try:
        from frontend.ui_web.plugin_host_api import prefs_plugin_get

        chosen = str((prefs_plugin_get(PLUGIN_ID) or {}).get("model_id") or "").strip()
    except Exception:  # noqa: BLE001 — prefs are best-effort
        chosen = ""
    return chosen or DEFAULT_MODEL


def _http_error_message(exc: urllib.error.HTTPError) -> str:
    body = ""
    try:
        body = exc.read().decode("utf-8", "replace")
    except Exception:  # noqa: BLE001
        body = ""
    detail = body
    try:
        parsed = json.loads(body)
        raw = parsed.get("detail") if isinstance(parsed, dict) else None
        if isinstance(raw, dict):
            detail = str(raw.get("message") or raw.get("status") or json.dumps(raw))
        elif isinstance(raw, str):
            detail = raw
    except (ValueError, TypeError):
        pass
    code = exc.code
    if code == 401:
        return "ElevenLabs rejected the API key (401). Re-check it in Settings → ElevenLabs."
    if code == 400 or code == 422:
        return f"ElevenLabs could not use that voice/model ({code}): {detail[:200]}"
    if code == 429:
        return "ElevenLabs quota or rate limit reached (429)."
    return f"ElevenLabs error {code}: {detail[:200]}"


def _synthesize(text: str, voice_id: str) -> dict[str, Any]:
    """text + voice id -> {ok, audio_base64, mime} (host plays the MP3)."""
    key = _api_key()
    if not key:
        return {"ok": False, "error": "No ElevenLabs API key — add it in Settings → ElevenLabs."}
    clean = (text or "").strip()
    if not clean:
        return {"ok": False, "error": "Nothing to speak"}
    voice = (voice_id or "").strip() or DEFAULT_VOICE_ID
    payload = json.dumps({"text": clean, "model_id": _model_id()}).encode("utf-8")
    req = urllib.request.Request(
        f"{API_BASE}/text-to-speech/{voice}",
        data=payload,
        method="POST",
        headers={
            "xi-api-key": key,
            "Content-Type": "application/json",
            "Accept": "audio/mpeg",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            audio = resp.read()
    except urllib.error.HTTPError as exc:
        return {"ok": False, "error": _http_error_message(exc)}
    except urllib.error.URLError as exc:
        return {"ok": False, "error": f"Network error reaching ElevenLabs: {exc.reason}"}
    except Exception as exc:  # noqa: BLE001 — never raise across the worker bridge
        return {"ok": False, "error": str(exc) or "ElevenLabs request failed"}
    if not audio:
        return {"ok": False, "error": "ElevenLabs returned empty audio"}
    return {
        "ok": True,
        "audio_base64": base64.b64encode(audio).decode("ascii"),
        "mime": "audio/mpeg",
    }


def _list_voices() -> list[dict[str, str]]:
    """Fetch the account's voices (premade + cloned/custom). Cached, fail-soft."""
    key = _api_key()
    if not key:
        return []
    key_fp = key[-6:]
    now = time.monotonic()
    if (
        _VOICE_CACHE["voices"]
        and _VOICE_CACHE["key_fp"] == key_fp
        and (now - float(_VOICE_CACHE["at"])) < _VOICE_TTL_SECONDS
    ):
        return list(_VOICE_CACHE["voices"])
    req = urllib.request.Request(
        f"{API_BASE}/voices",
        headers={"xi-api-key": key, "Accept": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, ValueError, TypeError) as exc:
        log.info("elevenlabs list voices failed: %s", exc)
        # Keep serving the last good list on a transient failure (only if same key).
        return list(_VOICE_CACHE["voices"]) if _VOICE_CACHE["key_fp"] == key_fp else []
    except Exception as exc:  # noqa: BLE001
        log.info("elevenlabs list voices error: %s", exc)
        return list(_VOICE_CACHE["voices"]) if _VOICE_CACHE["key_fp"] == key_fp else []
    out: list[dict[str, str]] = []
    for voice in (data.get("voices") or []) if isinstance(data, dict) else []:
        if not isinstance(voice, dict):
            continue
        vid = str(voice.get("voice_id") or "").strip()
        if not vid:
            continue
        name = str(voice.get("name") or vid).strip()
        category = str(voice.get("category") or "").strip()
        label = name if category in ("", "premade", "professional") else f"{name} · {category}"
        out.append({"id": vid, "label": label or vid})
    _VOICE_CACHE.update(at=now, key_fp=key_fp, voices=list(out))
    return out


def register(api) -> None:
    """Wire the ElevenLabs synthesizer + dynamic voice lister into the host."""
    api.register_tts(_synthesize)
    # register_tts_voices ships alongside this plugin — guard it so the plugin still
    # loads (premade voices keep working) on an app build that predates dynamic voices.
    register_voices = getattr(api, "register_tts_voices", None)
    if callable(register_voices):
        register_voices(_list_voices)
    api.log("ElevenLabs voices registered")
